version: '3'
services:
  vprodb:
    image: dshahi/vprofiledb:V1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vproddbpass
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  vpromq01:
    image rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER: guest
      - RABBITMY_DEFAULT_PASS: guest
  vproapp:
    image: dshahi/vprofileapp:V1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapp
  vproweb:
    image: dshahi/vprofileweb:V1
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
